name: 06 Events
on:
  # Pull Request Event
  pull_request:
    # specific Activity Types
    types:
      # Activity Type Name
      - opened
    # the Workflow will only trigger on a pull_request to the following branches:
    branches:
      - main
      - "dev-*" # dev-new1 dev-new2
      - "feat/**" # feat/new1 feat/new/button
  # Manually Triggered Event
  workflow_dispatch:
  # Push Event
  push:
    # the Workflow will only trigger when a push happens on the following branches:
    branches:
      - main
      - "dev-*" # dev-new1 dev-new2
      - "feat/**" # feat/new1 feat/new/button
    # files changed in the specified folder(s) will trigger the Workflow
    paths:
      - "03-project/**"
    # files in the specified folder(s) will not trigger the Workflow
    # if a file in the specified folder is changed this will prevent the Workflow from running (even if other files are changed)
    # paths-ignore:
    # - ".github/workflows/*"

# set the working directory for all run steps in the workflow (does not affect "uses" Actions)
defaults:
  run:
    working-directory: 03-project

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: echo "${{ toJSON(github.event) }}"
        # this step needs to run from the default directory because the 03-project folder doesn't exist yet
        working-directory: ${{ github.workspace }}
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test Code
        run: npm run test
      - name: Build Code
        run: npm run build
      - name: Deploy Code
        run: echo "Deploying..."
