name: 07 Artifacts
on:
  push:
    branches:
      - main

# set the working directory for all run steps in the workflow (does not affect "uses" Actions)
defaults:
  run:
    working-directory: 04-project

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Lint Code
        run: npm run lint
      - name: Test Code
        run: npm run test
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Build Code
        run: npm run build
        # This allows us to Upload Artifacts
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          # we give the Artifact a name, so we can retrieve it later
          name: dist-artifact
          # this defines which files you want to store
          path: 04-project/dist
  deploy:
    needs: build # we need this because otherwise the Artifact will not have been uploaded and so could not be downloaded
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          # we need to provide the Artifact identifier
          name: dist-artifact
      - name: Output Current Folder and Contents
        run: |
          pwd
          ls
      - name: Deploy Code
        run: echo "Deploying..."
        # this step needs to run from the default directory because the 03-project folder doesn't exist yet
        working-directory: ${{ github.workspace }}
