name: Deployment
on:
  push:
    branches:
      - main
      - dev
# Set the environment variables at the Workflow level
env:
  MONGO_DB_NAME: some-database-name
jobs:
  test:
    # Set the environment variables at the Job level
    env:
      MONGO_CLUSTER_ADDRESS: some-test-database-address
      MONGO_USERNAME: some-test-database-username
      MONGO_PASSWORD: some-test-database-password
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-deps-${{ hashFiles('./05-project/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Run server
        run: npm start & npx wait-on http://127.0.0.1:XYZ
      - name: Run tests
        run: npm test
      - name: Output information
        run: echo "..."
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        run: |
          echo "..."
