name: 08 Environment Variables & Secrets
on:
  push:
    branches:
      - main
      - dev
# Set the environment variables at the Workflow level
env:
  MONGODB_DB_NAME: some-database-name # some-database-name

jobs:
  test:
    # set the working directory for all run steps in the Job (does not affect "uses" Actions)
    defaults:
      run:
        working-directory: 05-project
    # Set the environment for this Job
    # The Secrets will now come from those set in this Environment in the GitHub Repository
    environment: testing
    # Set the environment variables at the Job level
    env:
      MONGODB_CLUSTER_ADDRESS: cluster0.3ekyupv.mongodb.net # some-test-database-address
      MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }} # some-test-database-username
      MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }} # some-test-database-password
      PORT: 4000 # some-api-server-port
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-deps-${{ hashFiles('./05-project/package-lock.json') }}
      - name: Install Dependencies
        run: npm ci
      - name: Run Server
        # we can use the Environment Variable here with interpolation $VARIABLE_NAME
        run: npm start & npx wait-on http://127.0.0.1:$PORT
      - name: Run Tests
        run: npm test
      - name: Output Information
        # we can use the Environment Variable here with GitHub Actions syntax
        run: |
          echo "MONGO_CLUSTER_ADDRESS: ${{ env.MONGODB_CLUSTER_ADDRESS}}"
          echo "MONGODB_USERNAME: ${{ env.MONGODB_USERNAME }}"
          echo "MONGODB_PASSWORD: ${{ env.MONGODB_PASSWORD }}"
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Output Information
        # the MONGODB_DB_NAME will be available here because it was defined at the Workflow level
        # but the MONGODB_USERNAME will NOT be available here because it was defined at the Job level in `test`
        run: |
          echo "MONGODB_DB_NAME: ${{ env.MONGODB_DB_NAME }}"
          echo "MONGODB_USERNAME: ${{ env.MONGODB_USERNAME }}"
